Iterate 0 to 10 using for loop, do the same using while loop.

In [3]:
for i in range(11):
    print(i)

i=0
while i <=10:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9
10
0
1
2
3
4
5
6
7
8
9
10

Iterate 10 to 0 using for loop, do the same using while loop.

In [17]:
for i in range(10,-1,-1):
    print(i)

i = 10
while i>=0:
    print(i)
    i -= 1

10
9
8
7
6
5
4
3
2
1
0
10
9
8
7
6
5
4
3
2
1
0

Write a loop that makes seven calls to print(), so we get on the output the following triangle:

  #
  ##
  ###
  ####
  #####
  ######
  #######

In [29]:
for i in range(7):
    for j in range(7):
        if i>j:
            print('#',end="")
    print('# ')

#
##
###
####
#####
######
#######

Use nested loops to create the following:

# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #

In [22]:
for i in range(8):
    for j in range(8):
        print('# ',end="")
    print('# ')

# # # # # # # # #
# # # # # # # # #
# # # # # # # # #
# # # # # # # # #
# # # # # # # # #
# # # # # # # # #
# # # # # # # # #
# # # # # # # # #

Print the following pattern:

0 x 0 = 0
1 x 1 = 1
2 x 2 = 4
3 x 3 = 9
4 x 4 = 16
5 x 5 = 25
6 x 6 = 36
7 x 7 = 49
8 x 8 = 64
9 x 9 = 81
10 x 10 = 100

In [30]:
for i in range(11):
    print('{} x {} = {}'.format(i,i,i*i))

0 x 0 = 0
1 x 1 = 1
2 x 2 = 4
3 x 3 = 9
4 x 4 = 16
5 x 5 = 25
6 x 6 = 36
7 x 7 = 49
8 x 8 = 64
9 x 9 = 81
10 x 10 = 100

Iterate through the list, ['Python', 'Numpy','Pandas','Django', 'Flask'] using a for loop and print out the items.

In [31]:
skills = ['Python', 'Numpy','Pandas','Django', 'Flask']
for skill in skills:
    print(skill)

Python
Numpy
Pandas
Django
Flask

Use for loop to iterate from 0 to 100 and print only even numbers

In [32]:
for i in range(101):
    if i%2 ==0 :
        print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100

Use for loop to iterate from 0 to 100 and print only odd numbers

In [33]:
for i in range(101):
    if i%2 !=0:
        print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99

Use for loop to iterate from 0 to 100 and print the sum of all numbers.
The sum of all numbers is 5050.

In [41]:
summation =0
for i in range(101):
    summation += i
    print(summation)

0
1
3
6
10
15
21
28
36
45
55
66
78
91
105
120
136
153
171
190
210
231
253
276
300
325
351
378
406
435
465
496
528
561
595
630
666
703
741
780
820
861
903
946
990
1035
1081
1128
1176
1225
1275
1326
1378
1431
1485
1540
1596
1653
1711
1770
1830
1891
1953
2016
2080
2145
2211
2278
2346
2415
2485
2556
2628
2701
2775
2850
2926
3003
3081
3160
3240
3321
3403
3486
3570
3655
3741
3828
3916
4005
4095
4186
4278
4371
4465
4560
4656
4753
4851
4950
5050

Use for loop to iterate from 0 to 100 and print the sum of all evens and the sum of all odds.

The sum of all evens is 2550. And the sum of all odds is 2500.

In [3]:
even_summation = 0
for i in range(101):
    if i%2 ==0:
        even_summation += i
        print(even_summation)
        
odd_summation = 0
for i in range(101):
    if i%2 !=0:
        odd_summation += i
        print(odd_summation)

0
2
6
12
20
30
42
56
72
90
110
132
156
182
210
240
272
306
342
380
420
462
506
552
600
650
702
756
812
870
930
992
1056
1122
1190
1260
1332
1406
1482
1560
1640
1722
1806
1892
1980
2070
2162
2256
2352
2450
2550
1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024
1089
1156
1225
1296
1369
1444
1521
1600
1681
1764
1849
1936
2025
2116
2209
2304
2401
2500

Go to the data folder and use the countries.py file. Loop through the countries and extract all the countries containing the word land.

In [19]:
import sys
sys.path.insert(1,'../data')

import countries
for country in countries.countries:
    if 'land' in country:
        print(country)

Finland
Iceland
Ireland
Marshall Islands
Netherlands
New Zealand
Poland
Solomon Islands
Swaziland
Switzerland
Thailand

This is a fruit list, ['banana', 'orange', 'mango', 'lemon'] reverse the order using loop.

In [4]:
fruits =  ['banana', 'orange', 'mango', 'lemon']
for fruit in fruits[::-1]:
    print(fruit)

lemon
mango
orange
banana

Go to the data folder and use the countries_data.py file.
What are the total number of languages in the data
Find the ten most spoken languages from the data
Find the 10 most populated countries in the world

In [14]:
import sys
sys.path.insert(1,'../data')
import countries_data



# What are the total number of languages in the data
languages = []
for country_data in countries_data.countries_data:
    languages.extend(country_data['languages'])
print("The total number of languages are: ",len(set(languages)))

# Find the ten most spoken languages from the data
for language in languages:
    print(language ,":",languages.count(language))


# Find the 10 most populated countries in the world
population = {}
for country_data in countries_data.countries_data:
    population[country_data['name']] = country_data['population']

print((population))

The total number of languages are:  112
Pashto : 1
Uzbek : 2
Turkmen : 2
Swedish : 3
Albanian : 3
Arabic : 25
English : 91
Samoan : 2
Catalan : 1
Portuguese : 9
English : 91
English : 91
Russian : 9
English : 91
Spanish : 24
Guaraní : 2
Armenian : 2
Russian : 9
Dutch : 8
(Eastern) Punjabi : 2
English : 91
German : 7
Azerbaijani : 1
English : 91
Arabic : 25
Bengali : 1
English : 91
Belarusian : 1
Russian : 9
Dutch : 8
French : 45
German : 7
English : 91
Spanish : 24
French : 45
English : 91
Dzongkha : 1
Spanish : 24
Aymara : 1
Quechua : 1
Dutch : 8
Bosnian : 2
Croatian : 3
Serbian : 4
English : 91
Tswana : 2
Norwegian : 3
Norwegian Bokmål : 2
Norwegian Nynorsk : 2
Portuguese : 9
English : 91
English : 91
English : 91
English : 91
Malay : 2
Bulgarian : 1
French : 45
Fula : 2
French : 45
Kirundi : 1
Khmer : 1
English : 91
French : 45
English : 91
French : 45
Portuguese : 9
English : 91
French : 45
Sango : 1
French : 45
Arabic : 25
Spanish : 24
Chinese : 5
English : 91
English : 91
Spanish : 24
Arabic : 25
French : 45
French : 45
Lingala : 2
French : 45
Lingala : 2
Kongo : 1
Swahili : 4
Luba-Katanga : 1
English : 91
Spanish : 24
Croatian : 3
Spanish : 24
Dutch : 8
(Eastern) Punjabi : 2
English : 91
Greek (modern) : 2
Turkish : 2
Armenian : 2
Czech : 1
Slovak : 2
Danish : 1
French : 45
Arabic : 25
English : 91
Spanish : 24
Spanish : 24
Arabic : 25
Spanish : 24
Spanish : 24
French : 45
Tigrinya : 1
Arabic : 25
English : 91
Estonian : 1
Amharic : 1
English : 91
Faroese : 1
English : 91
Fijian : 1
Hindi : 2
Urdu : 2
Finnish : 1
Swedish : 3
French : 45
French : 45
French : 45
French : 45
French : 45
English : 91
Georgian : 1
German : 7
English : 91
English : 91
Greek (modern) : 2
Kalaallisut : 1
English : 91
French : 45
English : 91
Chamorro : 2
Spanish : 24
Spanish : 24
English : 91
French : 45
French : 45
Fula : 2
Portuguese : 9
English : 91
French : 45
Haitian : 1
English : 91
Latin : 1
Italian : 4
French : 45
German : 7
Spanish : 24
English : 91
Chinese : 5
Hungarian : 1
Icelandic : 1
Hindi : 2
English : 91
Indonesian : 1
French : 45
Persian (Farsi) : 1
Arabic : 25
Kurdish : 1
Irish : 1
English : 91
English : 91
Manx : 1
Hebrew (modern) : 1
Arabic : 25
Italian : 4
English : 91
Japanese : 1
English : 91
French : 45
Arabic : 25
Kazakh : 1
Russian : 9
English : 91
Swahili : 4
English : 91
Arabic : 25
Kyrgyz : 1
Russian : 9
Lao : 1
Latvian : 1
Arabic : 25
French : 45
English : 91
Southern Sotho : 2
English : 91
Arabic : 25
German : 7
Lithuanian : 1
French : 45
German : 7
Luxembourgish : 1
Chinese : 5
Portuguese : 9
Macedonian : 1
French : 45
Malagasy : 1
English : 91
Chichewa : 1
Malaysian : 1
Divehi : 1
French : 45
Maltese : 1
English : 91
English : 91
Marshallese : 1
French : 45
Arabic : 25
English : 91
French : 45
Spanish : 24
English : 91
Romanian : 2
French : 45
Mongolian : 1
Serbian : 4
Bosnian : 2
Albanian : 3
Croatian : 3
English : 91
Arabic : 25
Portuguese : 9
Burmese : 1
English : 91
Afrikaans : 2
English : 91
Nauruan : 1
Nepali : 1
Dutch : 8
French : 45
English : 91
Māori : 1
Spanish : 24
French : 45
English : 91
English : 91
English : 91
Korean : 2
English : 91
Chamorro : 2
Norwegian : 3
Norwegian Bokmål : 2
Norwegian Nynorsk : 2
Arabic : 25
English : 91
Urdu : 2
English : 91
Arabic : 25
Spanish : 24
English : 91
Spanish : 24
Guaraní : 2
Spanish : 24
English : 91
English : 91
Polish : 1
Portuguese : 9
Spanish : 24
English : 91
Arabic : 25
Albanian : 3
Serbian : 4
French : 45
Romanian : 2
Russian : 9
Kinyarwanda : 1
English : 91
French : 45
French : 45
English : 91
English : 91
English : 91
English : 91
French : 45
Dutch : 8
French : 45
English : 91
Samoan : 2
English : 91
Italian : 4
Portuguese : 9
Arabic : 25
French : 45
Serbian : 4
French : 45
English : 91
English : 91
English : 91
Malay : 2
Tamil : 2
Chinese : 5
Dutch : 8
English : 91
Slovak : 2
Slovene : 1
English : 91
Somali : 1
Arabic : 25
Afrikaans : 2
English : 91
Southern Ndebele : 1
Southern Sotho : 2
Swati : 2
Tswana : 2
Tsonga : 1
Venda : 1
Xhosa : 1
Zulu : 1
English : 91
Korean : 2
English : 91
Spanish : 24
Sinhalese : 1
Tamil : 2
Arabic : 25
English : 91
Dutch : 8
Norwegian : 3
English : 91
Swati : 2
Swedish : 3
German : 7
French : 45
Italian : 4
Arabic : 25
Chinese : 5
Tajik : 1
Russian : 9
Swahili : 4
English : 91
Thai : 1
Portuguese : 9
French : 45
English : 91
English : 91
Tonga (Tonga Islands) : 1
English : 91
Arabic : 25
Turkish : 2
Turkmen : 2
Russian : 9
English : 91
English : 91
English : 91
Swahili : 4
Ukrainian : 1
Arabic : 25
English : 91
English : 91
Spanish : 24
Uzbek : 2
Russian : 9
Bislama : 1
English : 91
French : 45
Spanish : 24
Vietnamese : 1
French : 45
Spanish : 24
Arabic : 25
English : 91
English : 91
Shona : 1
Northern Ndebele : 1
{'Afghanistan': 27657145, 'Åland Islands': 28875, 'Albania': 2886026, 'Algeria': 40400000, 'American Samoa': 57100, 'Andorra': 78014, 'Angola': 25868000, 'Anguilla': 13452, 'Antarctica': 1000, 'Antigua and Barbuda': 86295, 'Argentina': 43590400, 'Armenia': 2994400, 'Aruba': 107394, 'Australia': 24117360, 'Austria': 8725931, 'Azerbaijan': 9730500, 'Bahamas': 378040, 'Bahrain': 1404900, 'Bangladesh': 161006790, 'Barbados': 285000, 'Belarus': 9498700, 'Belgium': 11319511, 'Belize': 370300, 'Benin': 10653654, 'Bermuda': 61954, 'Bhutan': 775620, 'Bolivia (Plurinational State of)': 10985059, 'Bonaire, Sint Eustatius and Saba': 17408, 'Bosnia and Herzegovina': 3531159, 'Botswana': 2141206, 'Bouvet Island': 0, 'Brazil': 206135893, 'British Indian Ocean Territory': 3000, 'United States Minor Outlying Islands': 300, 'Virgin Islands (British)': 28514, 'Virgin Islands (U.S.)': 114743, 'Brunei Darussalam': 411900, 'Bulgaria': 7153784, 'Burkina Faso': 19034397, 'Burundi': 10114505, 'Cambodia': 15626444, 'Cameroon': 22709892, 'Canada': 36155487, 'Cabo Verde': 531239, 'Cayman Islands': 58238, 'Central African Republic': 4998000, 'Chad': 14497000, 'Chile': 18191900, 'China': 1377422166, 'Christmas Island': 2072, 'Cocos (Keeling) Islands': 550, 'Colombia': 48759958, 'Comoros': 806153, 'Congo': 4741000, 'Congo (Democratic Republic of the)': 85026000, 'Cook Islands': 18100, 'Costa Rica': 4890379, 'Croatia': 4190669, 'Cuba': 11239004, 'Curaçao': 154843, 'Cyprus': 847000, 'Czech Republic': 10558524, 'Denmark': 5717014, 'Djibouti': 900000, 'Dominica': 71293, 'Dominican Republic': 10075045, 'Ecuador': 16545799, 'Egypt': 91290000, 'El Salvador': 6520675, 'Equatorial Guinea': 1222442, 'Eritrea': 5352000, 'Estonia': 1315944, 'Ethiopia': 92206005, 'Falkland Islands (Malvinas)': 2563, 'Faroe Islands': 49376, 'Fiji': 867000, 'Finland': 5491817, 'France': 66710000, 'French Guiana': 254541, 'French Polynesia': 271800, 'French Southern Territories': 140, 'Gabon': 1802278, 'Gambia': 1882450, 'Georgia': 3720400, 'Germany': 81770900, 'Ghana': 27670174, 'Gibraltar': 33140, 'Greece': 10858018, 'Greenland': 55847, 'Grenada': 103328, 'Guadeloupe': 400132, 'Guam': 184200, 'Guatemala': 16176133, 'Guernsey': 62999, 'Guinea': 12947000, 'Guinea-Bissau': 1547777, 'Guyana': 746900, 'Haiti': 11078033, 'Heard Island and McDonald Islands': 0, 'Holy See': 451, 'Honduras': 8576532, 'Hong Kong': 7324300, 'Hungary': 9823000, 'Iceland': 334300, 'India': 1295210000, 'Indonesia': 258705000, "Côte d'Ivoire": 22671331, 'Iran (Islamic Republic of)': 79369900, 'Iraq': 37883543, 'Ireland': 6378000, 'Isle of Man': 84497, 'Israel': 8527400, 'Italy': 60665551, 'Jamaica': 2723246, 'Japan': 126960000, 'Jersey': 100800, 'Jordan': 9531712, 'Kazakhstan': 17753200, 'Kenya': 47251000, 'Kiribati': 113400, 'Kuwait': 4183658, 'Kyrgyzstan': 6047800, "Lao People's Democratic Republic": 6492400, 'Latvia': 1961600, 'Lebanon': 5988000, 'Lesotho': 1894194, 'Liberia': 4615000, 'Libya': 6385000, 'Liechtenstein': 37623, 'Lithuania': 2872294, 'Luxembourg': 576200, 'Macao': 649100, 'Macedonia (the former Yugoslav Republic of)': 2058539, 'Madagascar': 22434363, 'Malawi': 16832910, 'Malaysia': 31405416, 'Maldives': 344023, 'Mali': 18135000, 'Malta': 425384, 'Marshall Islands': 54880, 'Martinique': 378243, 'Mauritania': 3718678, 'Mauritius': 1262879, 'Mayotte': 226915, 'Mexico': 122273473, 'Micronesia (Federated States of)': 102800, 'Moldova (Republic of)': 3553100, 'Monaco': 38400, 'Mongolia': 3093100, 'Montenegro': 621810, 'Montserrat': 4922, 'Morocco': 33337529, 'Mozambique': 26423700, 'Myanmar': 51419420, 'Namibia': 2324388, 'Nauru': 10084, 'Nepal': 28431500, 'Netherlands': 17019800, 'New Caledonia': 268767, 'New Zealand': 4697854, 'Nicaragua': 6262703, 'Niger': 20715000, 'Nigeria': 186988000, 'Niue': 1470, 'Norfolk Island': 2302, "Korea (Democratic People's Republic of)": 25281000, 'Northern Mariana Islands': 56940, 'Norway': 5223256, 'Oman': 4420133, 'Pakistan': 194125062, 'Palau': 17950, 'Palestine, State of': 4682467, 'Panama': 3814672, 'Papua New Guinea': 8083700, 'Paraguay': 6854536, 'Peru': 31488700, 'Philippines': 103279800, 'Pitcairn': 56, 'Poland': 38437239, 'Portugal': 10374822, 'Puerto Rico': 3474182, 'Qatar': 2587564, 'Republic of Kosovo': 1733842, 'Réunion': 840974, 'Romania': 19861408, 'Russian Federation': 146599183, 'Rwanda': 11553188, 'Saint Barthélemy': 9417, 'Saint Helena, Ascension and Tristan da Cunha': 4255, 'Saint Kitts and Nevis': 46204, 'Saint Lucia': 186000, 'Saint Martin (French part)': 36979, 'Saint Pierre and Miquelon': 6069, 'Saint Vincent and the Grenadines': 109991, 'Samoa': 194899, 'San Marino': 33005, 'Sao Tome and Principe': 187356, 'Saudi Arabia': 32248200, 'Senegal': 14799859, 'Serbia': 7076372, 'Seychelles': 91400, 'Sierra Leone': 7075641, 'Singapore': 5535000, 'Sint Maarten (Dutch part)': 38247, 'Slovakia': 5426252, 'Slovenia': 2064188, 'Solomon Islands': 642000, 'Somalia': 11079000, 'South Africa': 55653654, 'South Georgia and the South Sandwich Islands': 30, 'Korea (Republic of)': 50801405, 'South Sudan': 12131000, 'Spain': 46438422, 'Sri Lanka': 20966000, 'Sudan': 39598700, 'Suriname': 541638, 'Svalbard and Jan Mayen': 2562, 'Swaziland': 1132657, 'Sweden': 9894888, 'Switzerland': 8341600, 'Syrian Arab Republic': 18564000, 'Taiwan': 23503349, 'Tajikistan': 8593600, 'Tanzania, United Republic of': 55155000, 'Thailand': 65327652, 'Timor-Leste': 1167242, 'Togo': 7143000, 'Tokelau': 1411, 'Tonga': 103252, 'Trinidad and Tobago': 1349667, 'Tunisia': 11154400, 'Turkey': 78741053, 'Turkmenistan': 4751120, 'Turks and Caicos Islands': 31458, 'Tuvalu': 10640, 'Uganda': 33860700, 'Ukraine': 42692393, 'United Arab Emirates': 9856000, 'United Kingdom of Great Britain and Northern Ireland': 65110000, 'United States of America': 323947000, 'Uruguay': 3480222, 'Uzbekistan': 31576400, 'Vanuatu': 277500, 'Venezuela (Bolivarian Republic of)': 31028700, 'Viet Nam': 92700000, 'Wallis and Futuna': 11750, 'Western Sahara': 510713, 'Yemen': 27478000, 'Zambia': 15933883, 'Zimbabwe': 14240168}